all:
    echo "Check available recipes with just -l"
install:
    mamba env create -f env.yml &&\
    conda activate CIRIquant &&\
    mamba install -c conda-forge -c bioconda bwa=0.7.17 hisat2=2.2.0 stringtie=2.1.1 samtools=1.10 &&\
    mamba install -c conda-forge -c bioconda r-base=3.6 r-optparse=1.6.6 r-statmod=1.4.35 bioconductor-edger=3.28.0 bioconductor-limma=3.42.0 
test:
    #!/usr/bin/env bash
    set -euxo pipefail
    # CIRIquant 内部用的是 CIRI2.pl

    # wget https://github.com/Kevinzjy/CIRIquant/releases/download/v0.2.0/test_data.tar.gz
    # tar zxvf test_data.tar.gz

    source activate CIRIquant
    cd ./test_data/quant
    bwa index -a bwtsw -p chr1.fa chr1.fa
    hisat2-build ./chr1.fa ./chr1.fa

    CIRIquant -t 4 \
          -1 ./test_1.fq.gz \
          -2 ./test_2.fq.gz \
          --config ./chr1.yml \
          --no-gene \
          -o ./test \
          -p test
