all:
    echo "Check available recipes with just -l"
install:
    mamba create -n FindCirc -c conda-forge -c bioconda -y find_circ=1.2 bowtie2 samtools
test:
    #!/usr/bin/env bash
    set -euxo pipefail

    if [ ! -d ./find_circ ]; then
        echo "Clone the repo"
        git clone https://github.com/marvin-jens/find_circ
    fi
    cd find_circ/test_data
    source activate FindCirc
    make
